Added .aicoe-ci.yaml file
aicoe-aiops/HTM-applications pull request #19
Opened 2022-03-23 15:58 UTC by suppathak

After creating a repository on quay.io (https://github.com/operate-first/continuous-delivery/issues/32#issuecomment-1076472447). I have then updated the config file.

2022-03-23 16:38 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **suppathak** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aicoe-aiops%2FHTM-applications).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/aicoe-aiops/HTM-applications/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["suppathak"]} -->

2022-03-23 16:41 UTC, MichaelClifford commented
/approve

2022-03-23 16:48 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aicoe-aiops/HTM-applications/pull/19#issuecomment-1076555223" title="Approved">MichaelClifford</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aicoe-aiops%2FHTM-applications).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aicoe-aiops/HTM-applications/blob/master/OWNERS)~~ [MichaelClifford]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-03-23 17:18 UTC, sesheta commented
@suppathak: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | fe2ffb8432142df8bf94f6e9765e5652157a685f | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/aicoe-aiops_HTM-applications/19/pre-commit/1506679356712292352) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=aicoe-aiops&repo=HTM-applications&pr=19). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Asuppathak). Please help us and [open an issue](https://github.com/aicoe-aiops/HTM-applications/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-23 18:41 UTC, MichaelClifford commented
/retest

2022-03-23 18:55 UTC, harshad16 requested changes
one change required

2022-03-23 18:55 UTC, harshad16 commented on .aicoe-ci.yaml
> +  base-image: quay.io/thoth-station/s2i-custom-notebook:latest
is this application python 3.6 based ?
if not please use s2i-custom-py38-notebook

2022-03-23 18:56 UTC, harshad16 commented
/hold

2022-03-23 19:00 UTC, suppathak commented on .aicoe-ci.yaml
> +  base-image: quay.io/thoth-station/s2i-custom-notebook:latest
made the changes, thanks :+1:

2022-03-24 12:58 UTC, harshad16 commented
/unhold
/retest

2022-03-25 13:23 UTC, merged